#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;
modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," ./modorgnrn//alphasyndiffeq.mod");
    fprintf(stderr," ./modorgnrn//alphasynkin.mod");
    fprintf(stderr," ./modorgnrn//alphasynkint.mod");
    fprintf(stderr," ./modorgnrn//ampa.mod");
    fprintf(stderr," ./modorgnrn//ar.mod");
    fprintf(stderr," ./modorgnrn//cad.mod");
    fprintf(stderr," ./modorgnrn//ca_kloppenburg.mod");
    fprintf(stderr," ./modorgnrn//cal.mod");
    fprintf(stderr," ./modorgnrn//cat_a.mod");
    fprintf(stderr," ./modorgnrn//cat.mod");
    fprintf(stderr," ./modorgnrn//gabaa.mod");
    fprintf(stderr," ./modorgnrn//ggap.mod");
    fprintf(stderr," ./modorgnrn//iclamp_const.mod");
    fprintf(stderr," ./modorgnrn//k2.mod");
    fprintf(stderr," ./modorgnrn//kahp_deeppyr.mod");
    fprintf(stderr," ./modorgnrn//kahp.mod");
    fprintf(stderr," ./modorgnrn//kahp_slower.mod");
    fprintf(stderr," ./modorgnrn//ka_ib.mod");
    fprintf(stderr," ./modorgnrn//ka_kloppenburg.mod");
    fprintf(stderr," ./modorgnrn//ka.mod");
    fprintf(stderr," ./modorgnrn//kc_fast.mod");
    fprintf(stderr," ./modorgnrn//kc.mod");
    fprintf(stderr," ./modorgnrn//kdr_fs.mod");
    fprintf(stderr," ./modorgnrn//kdr.mod");
    fprintf(stderr," ./modorgnrn//kd_wustenberg.mod");
    fprintf(stderr," ./modorgnrn//km.mod");
    fprintf(stderr," ./modorgnrn//ks_kloppenburg.mod");
    fprintf(stderr," ./modorgnrn//naf2.mod");
    fprintf(stderr," ./modorgnrn//naf.mod");
    fprintf(stderr," ./modorgnrn//naf_tcr.mod");
    fprintf(stderr," ./modorgnrn//na_kloppenburg.mod");
    fprintf(stderr," ./modorgnrn//napf.mod");
    fprintf(stderr," ./modorgnrn//napf_spinstell.mod");
    fprintf(stderr," ./modorgnrn//napf_tcr.mod");
    fprintf(stderr," ./modorgnrn//nap.mod");
    fprintf(stderr," ./modorgnrn//par_ggap.mod");
    fprintf(stderr," ./modorgnrn//pulsesyn.mod");
    fprintf(stderr," ./modorgnrn//rampsyn.mod");
    fprintf(stderr," ./modorgnrn//rand.mod");
    fprintf(stderr," ./modorgnrn//region.mod");
    fprintf(stderr," ./modorgnrn//ri.mod");
    fprintf(stderr," ./modorgnrn//traub_nmda.mod");
    fprintf(stderr, "\n");
  }
  _alphasyndiffeq_reg();
  _alphasynkin_reg();
  _alphasynkint_reg();
  _ampa_reg();
  _ar_reg();
  _cad_reg();
  _ca_kloppenburg_reg();
  _cal_reg();
  _cat_a_reg();
  _cat_reg();
  _gabaa_reg();
  _ggap_reg();
  _iclamp_const_reg();
  _k2_reg();
  _kahp_deeppyr_reg();
  _kahp_reg();
  _kahp_slower_reg();
  _ka_ib_reg();
  _ka_kloppenburg_reg();
  _ka_reg();
  _kc_fast_reg();
  _kc_reg();
  _kdr_fs_reg();
  _kdr_reg();
  _kd_wustenberg_reg();
  _km_reg();
  _ks_kloppenburg_reg();
  _naf2_reg();
  _naf_reg();
  _naf_tcr_reg();
  _na_kloppenburg_reg();
  _napf_reg();
  _napf_spinstell_reg();
  _napf_tcr_reg();
  _nap_reg();
  _par_ggap_reg();
  _pulsesyn_reg();
  _rampsyn_reg();
  _rand_reg();
  _region_reg();
  _ri_reg();
  _traub_nmda_reg();
}
